blog/users/views.py
from flask import Blueprint, render_template
from flask_login import login_required
from werkzeug.exceptions import NotFound

from blog.models.models import Users

user = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')

USERS = {1: 'David', 2: 'Saymon', 3: 'Bryan'}



@user.route('/')
def user_list():
    users = Users.query.all()
    return render_template('users/list.html', data=users)

@login_required
@user.route('/<int:pk>')
def profile(pk: int):
    _user = Users.query.filter_by(id=pk).one_or_none()
    if not _user:
        raise NotFound(f"User #{_user} doesn't exist!")
    return render_template('users/profile.html', user_name=_user.username)

blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% block css %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        {% endblock %}

      <title>
        {% block title %} Blog app {% endblock %}
      </title>

  </head>

    <body>
    {% include 'navbar.html' %}
    <div class="container">
    {% block body %}
    {% endblock %}
    </div>


    {% block js %}
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}" ></script>
    {% endblock %}
    </body>

</html>

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.user_list')}}">Users list</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('articles.list')}}">Articles</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{{ url_for('author.list')}}">Authors</a>
        </li>
          <li class="nav-item">
              {% if current_user.is_authenticated %}
                <a class="nav-link" href="{{ url_for('auth.logout')}}">Logout</a>
              {% else %}
                  <a href="{{ url_for('auth.login') }}" class="nav-link {% if request.endpoint == 'auth.login'
                          -%}active
              {% endif %}">

            Login
            </a>
            {% endif %}
        </li>
                <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.register')}}">Register</a>
        </li>
      </ul>
    </div>
  </div>
</nav>