blog/forms/user.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, PasswordField, SubmitField


class UserBaseForm(FlaskForm):
    username = StringField("username", [validators.DataRequired()])
    email = StringField("Email Adress", [
                        validators.DataRequired(),
                        validators.Email(),
                        validators.Length(min=6, max=50)],
                        filters=[lambda data: data and data.lower()])


class RegistrationForm(UserBaseForm):
    password = PasswordField(
        "New Password", [validators.data_required(),
                         validators.EqualTo("confirm", message="Passwords must match")])
    confirm = PasswordField("Repeat password")
    submit = SubmitField("Register")


class LoginForm(FlaskForm):
    email = StringField(
        "email",
        [validators.DataRequired(),
         validators.Email(),
         validators.Length(min=6, max=50)],
    )
    password = PasswordField(
        "Password",
        [validators.DataRequired()],
    )
    submit = SubmitField("Login")

blog/users/views.py
from flask import Blueprint, render_template
from flask_login import login_required
from werkzeug.exceptions import NotFound

from blog.models.models import Users

user = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')

USERS = {1: 'David', 2: 'Saymon', 3: 'Bryan'}



@user.route('/')
def user_list():
    users = Users.query.all()
    return render_template('users/list.html', data=users)

@login_required
@user.route('/<int:pk>')
def profile(pk: int):
    _user = Users.query.filter_by(id=pk).one_or_none()
    if not _user:
        raise NotFound(f"User #{_user} doesn't exist!")
    return render_template('users/profile.html', user_name=_user.username)

blog/templates/users/details.html
{% extends 'base.html' %}

{% block title %}
    User details
{% endblock %}

{% block body %}
    <h1>{{ user_name }}</h1>
{% endblock %}

blog/templates/users/list.html
{% extends 'base.html'%}

{% block title %}
    Users list
{% endblock %}

{% block body %}
    <h1>Users list</h1>
        {% for user in data %}
            <ul>
                <li>
                    <a href="{{ url_for('user.profile', pk=user.id) }}">
                    {{ user.username }}
                    </a>
                </li>
            </ul>
        {% endfor %}
{% endblock %}

blog/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}
    User details
{% endblock %}

{% block body %}
    <h1>{{ user_name }}</h1>
{% endblock %}